Parameters:
  GoogleClientId:
    Type: String

  GoogleClientSecret:
    Type: String

  CustomDomainName:
    Type: String
    Default: auth.itononari.xyz

  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1


Resources:
  # User Pool
  MyAttendancePool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyAuthAttendance
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  # User Pool Client
  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: MyAuthAttendanceClient
      UserPoolId: !Ref MyAttendancePool
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        #認証するために必要
        - https://app.itononari.xyz/auth
      LogoutURLs:
        - https://app.itononari.xyz
      SupportedIdentityProviders:
        - COGNITO
        - Google
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  #User Pool Domain
  MyUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CustomDomainName
      UserPoolId: !Ref MyAttendancePool
      CustomDomainConfig:
        CertificateArn: !Ref CertificateArn

  # Google IdP
  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref MyAttendancePool
      ProviderDetails:
        client_id: !Ref GoogleClientId
        client_secret: !Ref GoogleClientSecret
        authorize_scopes: email profile openid
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name

  # うまくいかん。
  # MyCognitoBranding:
  #   Type: AWS::Cognito::ManagedLoginBranding
  #   Properties:
  #     Assets: 
  #       - Bytes: PHN2ZyB3aWR0aD0iMjAwMDAiIGhlaWdodD0iNDAwIiB2aWV3Qm94PSIwIDAgMjAwMDAgNDAwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8ZyBjbGlwLXBhdGg9InVybCgjY2xpcDBfMTcyNTlfMjM2Njc0KSI+CjxyZWN0IHdpZHRoPSIyMDAwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9InVybCgjcGFpbnQwX2xpbmVhcl8xNzI1OV8yMzY2NzQpIi8+CjxwYXRoIGQ9Ik0wIDBIMjAwMDBWNDAwSDBWMFoiIGZpbGw9IiMxMjIwMzciIGZpbGwtb3BhY2l0eT0iMC41Ii8+CjwvZz4KPGRlZnM+CjxsaW5lYXJHcmFkaWVudCBpZD0icGFpbnQwX2xpbmVhcl8xNzI1OV8yMzY2NzQiIHgxPSItODk0LjI0OSIgeTE9IjE5OS45MzEiIHgyPSIxODAzNC41IiB5Mj0iLTU4OTkuNTciIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iI0JGODBGRiIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNGRjhGQUIiLz4KPC9saW5lYXJHcmFkaWVudD4KPGNsaXBQYXRoIGlkPSJjbGlwMF8xNzI1OV8yMzY2NzQiPgo8cmVjdCB3aWR0aD0iMjAwMDAiIGhlaWdodD0iNDAwIiBmaWxsPSJ3aGl0ZSIvPgo8L2NsaXBQYXRoPgo8L2RlZnM+Cjwvc3ZnPgo=
  #         Category: PAGE_FOOTER_BACKGROUND
  #         ColorMode: DARK
  #         Extension: SVG
  #     ClientId: !Ref GoogleClientId
  #     UserPoolId: !Ref MyAttendancePool


Outputs:
  UserPoolDomain:
    Value: !GetAtt  MyUserPoolDomain.CloudFrontDistribution
    Description: This is the User Pool Domain for cognito
    Export: 
      Name: UserPoolDomain
  
  UserPoolId:
    Value: !Ref MyAttendancePool
    Description: This is the User Pool ID
    Export: 
      Name: UserPoolId
