
Resources:

  AttendanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AttendanceRecords
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: work_date
          AttributeType: S

      KeySchema:
        - AttributeName: user_id
          KeyType: HASH   # パーティションキー
        - AttributeName: work_date
          KeyType: RANGE  # ソートキー

      BillingMode: PAY_PER_REQUEST  # または PROVISIONED として Read/WriteCapacityUnits を指定
      Tags:
        - Key: Name
          Value: attendance-table
        - Key: Env
          Value: dev

  CredentialTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AccessAndUserManageRecord
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
        - AttributeName: lastaccesstime
          AttributeType: S

      KeySchema:
        - AttributeName: sub
          KeyType: HASH   # パーティションキー
        - AttributeName: lastaccesstime
          KeyType: RANGE  # ソートキー
          
      BillingMode: PAY_PER_REQUEST  # または PROVISIONED として Read/WriteCapacityUnits を指定
      Tags:
        - Key: Name
          Value: AccessAndUserManageRecord
        - Key: Env
          Value: dev

      TimeToLiveSpecification:
        AttributeName: expire_at
        Enabled: true


Outputs:
  AttendancetblArn:
    Value: !GetAtt AttendanceTable.Arn
    Description: Attendance Table Arn
    Export:
      Name: AttendancetblArn

  CredentialtblArn:
    Value: !GetAtt   CredentialTable.Arn
    Description: CredentialTable Arn
    Export:
      Name: CredentialtblArn