Parameters:
  SecretsManagerARN:
    Type: String
    Description: Into Secret Manager ARN. You have this one at us-east-1.
  UserPoolId:
    Type: String
    Description: Into User Pool Id that published by cognito app client.(ex. ap-northeast-1.xxxxxxxx)
  ClientId:
    Type: String
    Description: Into Client Id that published by cognito.
  RedirectURI:
    Type: String
    Description: Into URI for invoke lambda.
    Default: https://app.itononari.xyz/auth
  CognitoDomain:
    Type: String
    Description: Into cognito domain
    Default: auth.itononari.xyz

Resources:
  PostFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyAttendanceFunction
      Description: "This define the Lambda Function for post method"
      Code:
        S3Bucket: !ImportValue S3BucketName
        S3Key: lambda_function.py.zip
      Environment:
        Variables:
          bucket_name: !ImportValue S3BucketName
          secrets_manager_arn: !Ref SecretsManagerARN
      Role: !ImportValue LambdaRole
      Runtime: "python3.13"
      Handler: lambda_function.lambda_handler
      Timeout: 10
      Layers:
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:openpyxl-utils:1
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:openpyxl:3

  LambdaInvokePermissionForAPI:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
 
  DownloadFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyDownloadFileFunciton
      Description: "This define the Lambda Function for file download"
      Code:
        S3Bucket: !ImportValue S3BucketName
        S3Key: lambda_function.py.zip
      Environment:
        Variables:
          bucket_name: !ImportValue S3BucketName
          secrets_manager_arn: !Ref SecretsManagerARN
          template_filepath: "attendance/files/template/attendance_template.xlsx"
      Role: !ImportValue LambdaRole
      Runtime: "python3.13"
      Handler: lambda_function.lambda_handler
      Timeout: 20
      Layers:
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:openpyxl-utils:1
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:openpyxl:3

  LambdaInvokePermissionForDownload:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DownloadFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  AuthenticateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyAuthenticateFunciton
      Description: "This define the Lambda Function for Authentication"
      Code:
        S3Bucket: !ImportValue S3BucketName
        S3Key: auth_lambda_function.py.zip
      Environment:
        Variables:
          bucket_name: !ImportValue S3BucketName
          secrets_manager_arn: !Ref SecretsManagerARN
          userpoolid: !Ref UserPoolId
          clientid: !Ref ClientId
          redirecturi: !Ref RedirectURI
          cognitodomain: !Ref CognitoDomain
      Role: !ImportValue LambdaRole
      Runtime: "python3.13"
      Handler: auth_lambda_function.lambda_handler
      Timeout: 10
      Layers:
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:jwt:2
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:requests:1
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:cryptography:6
        

  LambdaInvokePermissionForAuth:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AuthenticateFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  CheckCredentialFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CheckCredentialFunction
      Description: "This Function for validation user access"
      Code:
        S3Bucket: !ImportValue S3BucketName
        S3Key: credential_lambda_function.py.zip
      Environment:
        Variables:
          secrets_manager_arn: !Ref SecretsManagerARN
          userpoolid: !Ref UserPoolId
          clientid: !Ref ClientId
      Role: !ImportValue CredentialLambdaRole
      Runtime: "python3.13"
      Handler: credential_lambda_function.lambda_handler
      Timeout: 10
      Layers:
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:jwt:2
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:rust:1
        - arn:aws:lambda:ap-northeast-1:324037284373:layer:cryptography:6

Outputs:
  FunctionARN:
    Value: !GetAtt PostFunction.Arn
    Description: Return Function arn
    Export:
      Name: FunctionARN

  DownloadFunctionARN:
    Value: !GetAtt DownloadFunction.Arn
    Description: Return Download Function arn
    Export:
      Name: DownloadFunctionARN

  AuthFunctionARN:
    Value: !GetAtt AuthenticateFunction.Arn
    Description: Return Authenticate Function arn
    Export:
      Name: AuthFunctionARN

  