Parameters:
  ImportedARN:
    Type: String
    Description: Insert IAM ROLE To Assume role to lambda
  LambdaARN:
    Type: String
    Description: Insert Lambda ARN to Access secrets manager

Resources:
  MySecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is the secrets manager for store my iam role arn
      Name: "snhxc"
      SecretString: !Sub |
          {
            "s3_access_role_arn": "${ImportedARN}"
          }
  SecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref MySecrets
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowLambdaAccess
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: secretsmanager:GetSecretValue
            Resource: !Ref MySecrets
            Condition:
              ArnLike:
                aws:SourceArn: !Ref LambdaARN
