Parameters:
  MyAppDomainName:
    Type: String
    Description: Please input domain name that you want to alternate cloud front domain name
    Default: app.itononari.xyz
  MyApiDomainName:
    Type: String
    Description: Please input domain name that you want to alternate cloud front domain name
    Default: api.itononari.xyz

Resources: 
  MyAppCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref MyAppDomainName
      ValidationMethod: DNS

  MyApiCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref MyApiDomainName
      ValidationMethod: DNS
